services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
    
    Harryn\Jacobn\MailboxBundle\:
        resource: '../../*'
        exclude: '../../{DependencyInjection,Entity,Package,Templates,Migrations,Tests}'
    
    Harryn\Jacobn\MailboxBundle\Controller\:
        resource: '../../Controller/*'
        tags: ['controller.service_arguments']
    
    Harryn\Jacobn\MailboxBundle\Console\:
        resource: '../../Console/*'
        exclude: '../../Console/{UTF8Symbol.php,ANSIEscapeSequence.php}'
    
    Harryn\Jacobn\MailboxBundle\EventListener\Swiftmailer:
        tags:
            - { name: jacobn.event_listener, event: swiftmailer.configuration.updated, method: onSwiftMailerConfigurationUpdated }
            - { name: jacobn.event_listener, event: swiftmailer.configuration.removed, method: onSwiftMailerConfigurationRemoved }
    
    # Public aliases
    jacobn.mailbox:
        public: true
        class: Harryn\Jacobn\MailboxBundle\Services\MailboxService
